## 1
name: Build Debug Apk and Deploy

## Actions that will be executed when pull request is created
on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  ## Debug
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # 3
      - name: Generate Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 4
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@master
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
